CREATE OR REPLACE FILE FORMAT my_csv_format
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null')
  EMPTY_FIELD_AS_NULL = true
;



DELETE  FROM IPL_APP.IPL_CORE.IPL_HISTORY;
COPY INTO IPL_APP.IPL_CORE.IPL_HISTORY
FROM @IPL_APP.EXTERNAL_STAGING.IPL_STG/ipl_historical.csv
FILE_FORMAT = (FORMAT_NAME='my_csv_format' DATE_FORMAT='DD/MM/YY');

SELECT * FROM IPL_APP.IPL_CORE.IPL_HISTORY;

COPY INTO IPL_APP.IPL_CORE.PARTNERSHIP_STATS
FROM @IPL_APP.EXTERNAL_STAGING.IPL_STG/ipl_partnership_card.csv
FILE_FORMAT = (FORMAT_NAME='my_csv_format');

select * from IPL_APP.IPL_CORE.PARTNERSHIP_STATS;

COPY INTO IPL_APP.IPL_CORE.FOW_CARD
FROM @IPL_APP.EXTERNAL_STAGING.IPL_STG/ipl_fow_card.csv
FILE_FORMAT = (FORMAT_NAME='my_csv_format');

select * from IPL_APP.IPL_CORE.FOW_CARD;


COPY INTO IPL_APP.IPL_CORE.BOWLING_STATS
FROM @IPL_APP.EXTERNAL_STAGING.IPL_STG/ipl_bowling_card.csv
FILE_FORMAT = (FORMAT_NAME='my_csv_format');

SELECT * FROM IPL_APP.IPL_CORE.BOWLING_STATS;


COPY INTO IPL_APP.IPL_CORE.BALL_BY_BALL_DATA
FROM @IPL_APP.EXTERNAL_STAGING.IPL_STG/ipl_ball_by_ball_data.csv
FILE_FORMAT = (FORMAT_NAME='my_csv_format');

SELECT * FROM IPL_APP.IPL_CORE.BALL_BY_BALL_DATA;


COPY INTO IPL_APP.IPL_CORE.PLAYER_INFO
FROM @IPL_APP.EXTERNAL_STAGING.IPL_STG/ipl_players_info.csv
FILE_FORMAT = (FORMAT_NAME='my_csv_format' DATE_FORMAT='DD/MM/YY');

SELECT * FROM IPL_APP.IPL_CORE.PLAYER_INFO;

select t.$7,h.Match_Date from @IPL_APP.EXTERNAL_STAGING.IPL_STG/ipl_historical.csv t
inner join IPL_APP.IPL_CORE.IPL_HISTORY h 
on  t.$3 = h.MATCH_ID
;
delete from IPL_APP.IPL_CORE.BATTING_STATS;

COPY INTO IPL_APP.IPL_CORE.BATTING_STATS
FROM @IPL_APP.EXTERNAL_STAGING.IPL_STG/ipl_batting_card.csv
FILE_FORMAT = (FORMAT_NAME='my_csv_format' DATE_FORMAT='DD/MM/YY');

SELECT * FROM IPL_APP.IPL_CORE.BATTING_STATS;

