CREATE OR REPLACE TABLE BOWLING_STATS(
player_id	NUMBER(38,0),
player_name	VARCHAR(100),
AGE	NUMBER(10,0),
batting_style	VARCHAR(50),
bowling_style	VARCHAR(50),
team	VARCHAR(50),
overs	NUMBER(10,0),
balls	NUMBER(38,0),
maidens	INTEGER,
wickets	INTEGER,
Strike_rate	DECIMAL(10,2),
ECONOMY	DECIMAL(10,2),
dots	INTEGER,
fours	NUMBER(10,0),
sixes	NUMBER(10,0),
wides	NUMBER(10,0),
noballs	NUMBER(10,0));